server:
  port: 8080


spring:
  application:
    name: Copa do Mundo
  datasource:
    url: jdbc:mariadb://localhost:3307/copadomundo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false



